let articles = {
    data: [
        {
            Title: "Understanding Bleeding Injuries: A Guide for Children", image: "../imgs/articles/article1.png",
            category1: "all", category2: "0-18", id: "1",
            Description: "Bleeding injuries can occur during emergencies, including war. Learning how to recognize and respond to these injuries is crucial.",
            Content: "Bleeding injuries can result from various situations, including accidents or violence. For children, understanding the basics of how to respond to bleeding can be life-saving. In emergency situations, it’s essential to remain calm and seek help. Children should be taught to recognize when someone is bleeding and to call for an adult or emergency services immediately. By learning these steps, kids can help ensure that injured individuals receive prompt attention. If a child witnesses a bleeding injury, there are simple first aid steps they can follow.Applying direct pressure to the wound with a clean cloth or bandage can help slow the bleeding.If the blood soaks through, it’s important not to remove the original cloth but to add more layers on top.This method helps to control the bleeding until professional help arrives.Additionally, keeping the injured person calm can prevent further complications. Education about emergency response can empower children to act in crisis situations.Schools and community programs can offer training on basic first aid techniques, including dealing with bleeding injuries.By fostering awareness and preparedness, children can feel more confident in their ability to respond effectively in emergencies, potentially saving lives.",
        },
        {
            Title: "Understanding and Managing Bleeding Injuries During Pregnancy in War Zones", image: "../imgs/articles/article2.jpg",
            category1: "woman", category2: "16-60", id: "2",
            Description: "Pregnant women are at increased risk during conflicts. Knowing how to manage bleeding can be vital for both mother and baby.",
            Content: "During times of conflict, pregnant women may experience bleeding injuries from falls or violent encounters. These situations pose severe risks to both the mother and the unborn child. Understanding the signs of complications, such as heavy bleeding or severe abdominal pain, is critical. If a pregnant woman experiences significant bleeding, it is essential to seek medical help immediately, as it can indicate a life-threatening condition such as placental abruption or uterine rupture.Managing bleeding in pregnant women requires immediate action.Apply direct pressure to the wound and elevate the legs to help minimize blood loss.If the woman feels faint or lightheaded, lying down and keeping her head lower than her heart can be beneficial.These measures can stabilize her condition while waiting for professional medical assistance.Family members and caregivers should be aware of the need for rapid transport to a medical facility if serious injuries occur.Preventive strategies are crucial for protecting pregnant women in conflict zones.Access to safe shelters, education about recognizing the signs of complications, and having emergency medical contacts readily available can significantly improve outcomes.Community support and resources for pregnant women in these situations are vital for ensuring the safety and health of mothers and their babies.",
        },
        {
            Title: "Understanding Chemical Burns: Risks and Responses in Conflict Zones", image: "../imgs/articles/article3.png",
            category1: "all", category2: "16-60", id: "3",
            Description: "Chemical burns can result from exposure to warfare agents. Recognizing the signs and knowing how to respond is critical.",
            Content: "Chemical burns from warfare agents pose severe risks to individuals in conflict zones. These burns can result from exposure to toxic substances released during attacks, leading to severe skin damage and respiratory issues. Understanding the nature of chemical agents, such as mustard gas or nerve agents, is essential for recognizing symptoms. Immediate symptoms may include redness, blistering, and severe pain in affected areas, as well as difficulty breathing if inhaled.In the event of chemical exposure, removing the individual from the contaminated area is paramount.Rinsing the affected skin with copious amounts of water can help reduce the severity of burns.If clothing is contaminated, it should be removed carefully to prevent further skin contact.Always seek immediate medical attention, as chemical burns can have long- term effects and require specialized treatment.Time is critical in managing these injuries effectively.Education and preparedness can play a vital role in minimizing the impact of chemical burns.Communities in conflict areas should be equipped with resources and training to respond effectively to chemical exposures.Training on recognizing symptoms and implementing emergency measures can save lives and reduce the risk of long- term health issues.By fostering awareness and preparation, individuals can protect themselves and their loved ones during crises.",
        },
        {
            Title: "Coping with Amputation: Understanding and Recovery After War Injuries", image: "../imgs/articles/article4.png",
            category1: "all", category2: "16-60", id: "4",
            Description: "Amputation can result from severe injuries during conflicts. Understanding the implications and recovery strategies is essential.",
            Content: "Amputation is a devastating consequence of traumatic injuries in warfare, often resulting from explosive devices or gunfire. Individuals who experience amputations face not only physical challenges but also emotional and psychological impacts. Understanding the process of amputation, including the immediate medical response and long-term rehabilitation, is crucial for those affected. Access to quality medical care and support services can significantly influence recovery outcomes.Following an amputation, immediate medical care is vital to manage pain and prevent infection. Rehabilitation involves physical therapy to help regain strength and mobility. Psychological support is equally important, as individuals may struggle with grief, identity loss, and adjusting to new realities. Support groups and counseling can provide valuable resources for emotional healing and connection with others who have faced similar challenges.Preventive measures in conflict zones can help reduce the risk of traumatic injuries leading to amputation. Community education about the dangers of landmines and unexploded ordnance can promote safety awareness. Advocacy for victim assistance programs can ensure that individuals who suffer traumatic injuries receive the necessary care and support for recovery. By fostering a culture of awareness and preparedness, communities can work towards minimizing the impact of war-related injuries.",
        },
        {
            Title: "Understanding Gunshot Wounds: Safety and Response", image: "../imgs/articles/article5.jpg",
            category1: "all", category2: "0-18", id: "5",
            Description: "Gunshot wounds can occur in conflict areas. Learning how to respond to these injuries can save lives.",
            Content: "Gunshot wounds are among the most severe injuries encountered in war zones. Children must understand that in dangerous situations, their safety is the top priority. If a child witnesses a shooting or is injured, knowing how to react is crucial. Teaching children to seek immediate help from adults or emergency services can be life-saving. By emphasizing the importance of staying calm and following instructions, children can learn to act appropriately in emergencies. In the case of a gunshot wound, it’s essential to call for help and ensure the scene is safe before approaching the injured person. Applying direct pressure to the wound can help control bleeding. If the bleeding is severe, a tourniquet may be necessary, but only if trained to do so. Keeping the injured person calm and still is crucial to prevent further injury. Recognizing the signs of shock, such as pale skin or confusion, is important, and seeking medical help is imperative.Educating children about the realities of gun violence and the importance of safety can foster awareness in communities. Schools and local organizations can implement programs that teach conflict resolution, awareness of surroundings, and emergency response techniques. By empowering children with knowledge and skills, they can contribute to a culture of safety and preparedness, ultimately saving lives in critical situations.",
        },
        {
            Title: "Understanding Injuries from Explosive Devices in Warfare", image: "../imgs/articles/article6.png",
            category1: "all", category2: "16-60", id: "6",
            Description: "Explosive devices can cause devastating injuries. Knowing how to respond is critical for survival.",
            Content: "Injuries from explosive devices, such as landmines and improvised explosive devices (IEDs), are prevalent in conflict zones, often resulting in severe trauma and life-altering injuries. Individuals who encounter these devices may face critical conditions, including amputations, burns, and internal injuries. Awareness of the potential risks associated with explosive devices is essential for individuals living or working in affected areas. Recognizing the sounds and sights associated with explosives can help individuals avoid dangerous situations.In the aftermath of an explosion, immediate first aid is crucial. Assessing the extent of injuries and providing basic care, such as controlling bleeding and ensuring the person’s airway is clear, is essential. If the individual is conscious, reassuring them can help reduce anxiety. Seeking professional medical assistance should be a priority, as injuries from explosive devices often require specialized care and surgical intervention.Preventing injuries from explosive devices involves community education and awareness. Training programs focused on identifying hazardous areas and promoting safety measures can significantly reduce risks. Advocacy for the removal of landmines and unexploded ordnance is critical for protecting civilians in conflict zones. By fostering a culture of safety and preparedness, communities can work together to mitigate the impacts of explosive-related injuries.",
        },
        {
            Title: "Addressing Trauma: Supporting the Elderly in Conflict Zones", image: "../imgs/articles/article7.jpg",
            category1: "all", category2: "16-60", id: "7",
            Description: " The elderly are particularly vulnerable to trauma during conflicts. Understanding their needs is crucial for providing support",
            Content: "The elderly face heightened risks during conflicts, as they may have limited mobility and health issues that complicate their response to traumatic events. Trauma from violence, displacement, and loss can severely impact their physical and mental well-being. It is essential for caregivers and community members to recognize the signs of trauma, such as anxiety, withdrawal, or changes in behavior, to provide appropriate support. Understanding their vulnerabilities allows for better intervention and care. In managing trauma, creating a supportive environment is vital. Encouraging open communication about experiences and feelings can help elderly individuals process their trauma. Professional counseling services tailored to the needs of the elderly can provide therapeutic support, helping them cope with their experiences. Involving family members in the healing process can strengthen support networks and promote resilience. Community initiatives aimed at supporting the elderly during conflicts are essential for their well-being. Establishing safe spaces for elderly individuals to gather, share experiences, and receive assistance can foster a sense of community and belonging. Providing resources, such as food, medical care, and emotional support, can help address the complex needs of elderly individuals facing trauma in conflict zones. By prioritizing their care and support, communities can help the elderly navigate the challenges of conflict more effectively.",
        },
        {
            Title: "Navigating Shrapnel Injuries: Prevention and Care in War Zones", image: "../imgs/articles/article8.jpg",
            category1: "all", category2: "16-60", id: "8",
            Description: " Shrapnel injuries can be devastating in conflicts. Recognizing risks and knowing how to respond is vital for safety.",
            Content: "Shrapnel injuries, often resulting from explosive devices, pose significant risks to individuals in conflict zones. These injuries can lead to severe trauma, including deep lacerations, internal damage, and even death. Understanding the nature of shrapnel and the dangers it presents is crucial for individuals living in or traveling to war-affected areas. Awareness of the signs of injury, such as intense pain, bleeding, and difficulty moving limbs, can help individuals act quickly in emergencies. In the event of a shrapnel injury, immediate first aid is essential. Controlling bleeding by applying direct pressure is the first step, followed by seeking medical help. If the shrapnel is visible and not embedded deeply, it may be carefully removed, but only if trained to do so. Individuals should never attempt to remove deeply embedded shrapnel, as this can worsen injuries. Professional medical assessment and treatment are critical for managing shrapnel injuries and preventing complications.Preventive measures are key to reducing the risk of shrapnel injuries in conflict zones. Education programs focusing on situational awareness, recognizing the signs of danger, and promoting safe behavior can help protect individuals. Advocating for conflict resolution and support for victims of violence is crucial for addressing the broader implications of war-related injuries. By fostering awareness and preparedness, communities can work towards reducing the impact of shrapnel injuries and improving safety in conflict areas.",
        },
        {
            Title: "Gunshot Wounds in Combat: Risks and Response for Men", image: "../imgs/articles/article9.png",
            category1: "Men", category2: "16-60", id: "9",
            Description: " Understanding the implications and treatment of gunshot wounds is essential for men in conflict zones, particularly in combat situations where they are often primary targets.",
            Content: "In conflict zones, males, particularly those engaged in combat, face a heightened risk of gunshot wounds. These injuries not only pose immediate physical threats but also carry significant psychological impacts. Males are often in frontline roles, increasing their exposure to gunfire and other violent encounters. The experience of being shot can lead to feelings of vulnerability, fear, and trauma, making awareness and preparation critical for survival and recovery. The severity of gunshot wounds can vary widely, with factors such as bullet type, range, and the location of the injury playing crucial roles. Common locations for gunshot wounds in males include the chest, abdomen, and limbs, with injuries to vital organs potentially leading to rapid blood loss and shock. Immediate first aid measures are vital; applying pressure to the wound and calling for emergency help can save lives. Knowing how to recognize life-threatening symptoms, such as difficulty breathing or excessive bleeding, can make a difference in the outcome. Moreover, addressing the psychological ramifications of gunshot injuries is equally important for men. The mental health challenges following such traumatic experiences can lead to conditions like PTSD, anxiety, or depression. Community support and access to mental health services can aid in recovery and help men cope with their experiences. Developing programs that focus on resilience and mental well-being, alongside practical training in first aid and emergency response, can empower men to navigate the dangers of combat effectively. By fostering a supportive environment, we can ensure that men are equipped to handle the physical and emotional consequences of gunshot wounds in conflict situations.",
        },
    ],
};


document.querySelectorAll('.article_link').forEach(link => {
    link.addEventListener('click', function (event) {
        const ID_value = event.currentTarget.getAttribute('id');
        const selectedArticle = articles.data.find(article => article.id === ID_value);

        console.log(ID_value);

        if (selectedArticle) {
            localStorage.setItem('articleTitle', selectedArticle.Title);
            localStorage.setItem('articleDescription', selectedArticle.Description);
            localStorage.setItem('articleContent', selectedArticle.Content);
            localStorage.setItem('pic', selectedArticle.image);
        }

        window.location.href = '../HTML/article.html';

    });
});